"""add attendance session and audit log

Revision ID: a0afd42f093d
Revises: 961321d4f572
Create Date: 2026-02-21 03:15:48.844302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0afd42f093d'
down_revision: Union[str, Sequence[str], None] = '961321d4f572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('session_opened', 'session_closed', 'checkin_success', 'checkin_failed', 'fraud_attempt', name='audit_event_type'), nullable=False),
    sa.Column('action_source', sa.Enum('device', 'api', 'system', name='audit_action_source'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_sessions',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_session_per_section', 'attendance_sessions', ['section_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.add_column('attendance_events', sa.Column('attendance_session_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_attendance_student_session', 'attendance_events', ['student_id', 'attendance_session_id'])
    op.create_foreign_key('fk_attendance_events_session_id', 'attendance_events', 'attendance_sessions', ['attendance_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attendance_events_session_id', 'attendance_events', type_='foreignkey')
    op.drop_constraint('uq_attendance_student_session', 'attendance_events', type_='unique')
    op.drop_column('attendance_events', 'attendance_session_id')
    op.drop_index('uq_active_session_per_section', table_name='attendance_sessions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('attendance_sessions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
